# Generated by Django 6.0.2 on 2026-03-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('unit', models.CharField(choices=[('sqft', 'Square Feet'), ('sqm', 'Square Meter')], max_length=10)),
                ('floors', models.IntegerField()),
                ('location_type', models.CharField(choices=[('metro', 'Metro City'), ('tier2', 'Tier 2 City'), ('rural', 'Rural Area')], max_length=20)),
                ('base_cost', models.FloatField()),
                ('material_breakdown', models.JSONField()),
                ('total_cost', models.FloatField()),
                ('gpt_explanation', models.TextField(blank=True, null=True)),
                ('token_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
